In [1]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import numpy as np
import pandas as pd

In [2]:
actual_data = np.ones(5)
actual_data

array([1., 1., 1., 1., 1.])

In [4]:
actual_data[-2:] = 0
actual_data

array([1., 1., 1., 0., 0.])

In [6]:
predicted_data = np.ones(5)
predicted_data

array([1., 1., 1., 1., 1.])

In [7]:
predicted_data[-1] = 0
predicted_data

array([1., 1., 1., 1., 0.])

In [11]:
m= confusion_matrix(predicted_data, actual_data)
m

array([[1, 0],
       [1, 3]], dtype=int64)

In [16]:
import seaborn as sns
import matplotlib.pyplot as plt

In [17]:
sns.heatmap(m, annot=True)
plt.show()

In [20]:
report = classification_report(actual_data, predicted_data)
print(report)

              precision    recall  f1-score   support

         0.0       1.00      0.50      0.67         2
         1.0       0.75      1.00      0.86         3

    accuracy                           0.80         5
   macro avg       0.88      0.75      0.76         5
weighted avg       0.85      0.80      0.78         5

